APT::FTPArchive::Release {
  Origin "berbascum";
  Label "berbascum";
  Suite "sid";
  Codename "sid";
  Architectures "all" "arm64" "amd64";
  Components "main";
  Description "Berb APT git repo";
};
